name: Deploy API app on production

on:
  push:
    branches:
      - feat/ba_dong/page_contact_and_survey
    # paths:
    #   - 'apps/api'

permissions:
  contents: read

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create .env file in ORM
        run: |
          printf 'DATABASE_URL="${{ secrets.DATABASE_URL }}"' > ./packages/orm-util/.env

      - name: Cope package.text to package.json
        run: |
          cp ./packages/orm-util/package.text ./packages/orm-util/package.json

      - name: Check package.json file
        run: cat ./packages/orm-util/package.json

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: apps/api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/turbo-api:latest
          build-args: DATABASE_URL=${{ secrets.DATABASE_URL }}

  deploy:
    name: Deploy to Azure Web App
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "di-landing-api"
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: "docker.io/${{ secrets.DOCKER_USERNAME }}/turbo-api:latest"

  notify-teams:
    runs-on: ubuntu-latest
    needs: deploy
    if: always()
    steps:
      - name: "Post deployment status API"
        uses: Data-Impact-VN/DI-GhActionTeamNotify@master
        if: always()
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
          job: ${{ toJson(job) }}
